version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monefyy-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      retries: 10
      timeout: 2s

  server:
    build: ./server
    container_name: monefyy_server
    env_file:
      - ./server/.env.development
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build: ./client
    container_name: monefyy_client
    depends_on:
     - server
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      -  /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]